#本地环境
spring:
  profiles: local
minio:
  endpoint: http://192.168.31.162:9000
  accessKey: minioadmin
  secretKey: minioadmin

  bootstrap checks failed
  [1]: max file descriptors [4096] for elasticsearch process is too low, increase to at least [65535]
  [2]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
  [3]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured

ERROR: [1] bootstrap checks failed
  [1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured