server:
  port: 8080

spring:
  application:
    name: spring-boot-shiro-jedis
  datasource:
    name: ShiroJwt
    url: jdbc:mysql://47.112.159.245:13306/shirojwt?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  #redis配置开始
  redis:
    # Redis服务器地址
    host: 192.168.31.162
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    #redis配置结束
    block-when-exhausted: true
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 6
        # 连接池最大连接数（使用负值表示没有限制）默认8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最小空闲连接
        min-idle: 0
  # 404交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  # 404交给异常处理器处理
  resources:
    add-mappings: false

mybatis:
  # Mybatis配置Mapper路径
  mapper-locations: classpath:mapper/*.xml
  # Mybatis配置Model类对应
  type-aliases-package: com.wang.model.entity

pagehelper:
  params: count=countSql
  # 指定分页插件使用哪种方言
  helper-dialect: mysql
  # 分页合理化参数 pageNum<=0时会查询第一页 pageNum>pages(超过总数时) 会查询最后一页
  reasonable: 'true'
  support-methods-arguments: 'true'

mapper:
  # 通用Mapper的insertSelective和updateByPrimaryKeySelective中是否判断字符串类型!=''
  not-empty: true

logging:
  # Debug打印SQL
  level.com.wang.mapper: debug

# 自定义
# AES密码加密私钥(Base64加密)
encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
# JWT认证加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
# AccessToken过期时间-5分钟-5*60(秒为单位)
accessTokenExpireTime: 300
# RefreshToken过期时间-30分钟-30*60(秒为单位)
refreshTokenExpireTime: 1800
# Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
shiroCacheExpireTime: 300