#服务端口号
server:
  port: 8080 #原来是http的8080

spring:
  application:
    name: dianjiu-blog
  profiles: local #开发环境

ncun:
  blog:
    name: DianJiu Blog
    desc: Learn Java Nodes
    site: https://dianjiu.top