#服务端口号
server:
  port: 8080 #原来是http的8080

spring:
  application:
    name: spring-boot-redis-jedis
  profiles: local #开发环境
  #redis配置开始
  redis:
    # Redis服务器地址
    host: 10.1.109.97
    # Redis服务器连接端口
    port: 8001
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 10000
    #redis配置结束
    block-when-exhausted: true
    jedis:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 6
        # 连接池最大连接数（使用负值表示没有限制）默认8
        max-active: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100
        # 连接池中的最小空闲连接
        min-idle: 0